[Writable]
LogLevel = "INFO"

[Service]
Host = "device-camera-go"
Port = 49985
ConnectRetries = 3
Labels = []
OpenMsg = "Device Camera Go Started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Type = "consul"
Host = "localhost"
Port = 8500
CheckInterval = "15s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Logging]
EnableRemote = false
File = "./device-camera-go-service.log"

[Credentials]
User = "camera_viewer"
Pass = "your_secure_password"

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Example declaration of pre-defined Devices - 
#  useful for tests or to to expedite device discovery
#  populate with static camera addresses; or devices otherwise known at deployment time
[[DeviceList]]
  Name = "MockAxisCamera001"
  Profile = "camera-profile-axis"
  Description = "Initial Axis camera configured on service startup"
  Labels = [ "camera", "axis" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = "axis001"
    Port = "49990"

[[DeviceList]]
  Name = "MockAxisCamera002"
  Profile = "camera-profile-axis"
  Description = "Initial Axis camera configured on service startup"
  Labels = [ "camera", "axis" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = "axis002"
    Port = "49990"
